//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventSpaceFinderEntities : DbContext
    {
        public EventSpaceFinderEntities()
            : base("name=EventSpaceFinderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<KalendarZauzetosti> KalendarZauzetostis { get; set; }
        public virtual DbSet<Komentar> Komentars { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Ocjena> Ocjenas { get; set; }
        public virtual DbSet<OmiljeniProstor> OmiljeniProstors { get; set; }
        public virtual DbSet<Paket> Pakets { get; set; }
        public virtual DbSet<Prostor> Prostors { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<SlikaProstora> SlikaProstoras { get; set; }
        public virtual DbSet<StatusRezervacije> StatusRezervacijes { get; set; }
        public virtual DbSet<TipDogadjaja> TipDogadjajas { get; set; }
        public virtual DbSet<Usluga> Uslugas { get; set; }
    }
}
