//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class KalendarZauzetosti
    {
        public int id_kalendara { get; set; }
        public int id_prostora { get; set; }
        public Nullable<int> id_rezervacije { get; set; }
        public System.DateTime datum { get; set; }
        public string status_datuma { get; set; }
        public string napomena { get; set; }
    
        public virtual Prostor Prostor { get; set; }
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
