//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public int id_ocjene { get; set; }
        public int id_korisnika { get; set; }
        public int id_prostora { get; set; }
        public int ocjena1 { get; set; }
        public System.DateTime datum_ocjene { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Prostor Prostor { get; set; }
    }
}
