//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paket()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Uslugas = new HashSet<Usluga>();
        }
    
        public int id_paketa { get; set; }
        public int id_prostora { get; set; }
        public string naziv_paketa { get; set; }
        public string opis { get; set; }
        public decimal cijena { get; set; }
        public int broj_sati { get; set; }
        public bool aktivan { get; set; }
    
        public virtual Prostor Prostor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usluga> Uslugas { get; set; }
    }
}
