//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.KalendarZauzetostis = new HashSet<KalendarZauzetosti>();
        }
    
        public int id_rezervacije { get; set; }
        public int id_korisnika { get; set; }
        public int id_prostora { get; set; }
        public int id_paketa { get; set; }
        public int id_statusa { get; set; }
        public System.DateTime datum_rezervacije { get; set; }
        public System.DateTime datum_dogadjaja { get; set; }
        public int broj_gostiju { get; set; }
        public decimal ukupna_cijena { get; set; }
        public string napomena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KalendarZauzetosti> KalendarZauzetostis { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Paket Paket { get; set; }
        public virtual Prostor Prostor { get; set; }
        public virtual StatusRezervacije StatusRezervacije { get; set; }
    }
}
