//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikaProstora
    {
        public int id_slike { get; set; }
        public int id_prostora { get; set; }
        public string putanja_slike { get; set; }
        public string opis { get; set; }
        public bool glavna_slika { get; set; }
    
        public virtual Prostor Prostor { get; set; }
    }
}
